### PR TITLE
Fix insertion bug in node_query_

### LINKED ISSUE #12: KDTree built with MSVC (Microsoft Visual C++) does not achieve 100% accuracy
### Environment
- crvs/KDTree (latest)
- gcc 9.4.0
- MSVC 14.40.33810

### Issue
KDTree built with gcc is 100% accurate, but when built with MSVC (Visual Studio 2022), the accuracy somehow drops.
I reproduced this phenomenon in error_test.cpp.
(The original code aborts the test if 100% accuracy is not achieved, but I modified it to continue.)

```sh
 > . \bin\Release\error_test.exe
 Total number of iterations ran: 30
 Accuracy (tested with 50 datasets per iter): 92.9333%. Total Number of correct queries: 46 / 50
 Total query time: { bruteForce: 0.0052009, kdTree: 0.0023472 }
 Accuracy (tested with 500 datasets per iter): 96.8733%. Total Number of correct queries: 484 / 500
 Total query time: { bruteForce: 0.491479, kdTree: 0.0470063 }
 Accuracy (tested with 1000 datasets per iter): 97.17%. Total Number of correct queries: 971 / 1000
 Total query time: { bruteForce: 1.98447, kdTree: 0.120078 }
```

### Minimal reproducible example
I modified toy_test.cpp to create a simple example
Strangely, the error does not always occur on the same input. That is, a single query may give the correct result, but some of the results may be wrong after ~100 runs.
(In the lucky case, the test program does not produce errors. If you want to reproduce it, please try running it several times.)

```cpp
#include <iostream>
#include <vector>
#include "KDTree.hpp"

int main() {
    pointVec points;
    points.push_back(point_t{ 0.0, 0.0 });
    points.push_back(point_t{ 1.0, 0.0 });
    points.push_back(point_t{ 0.0, 1.0 });
    points.push_back(point_t{ 1.0, 1.0 });
    points.push_back(point_t{ 0.5, 0.5 });
    KDTree tree(points);
    point_t pt { 0.8, 0.2 };
    point_t ground_truth { 1.0, 0.0 };
    std::cout << "query point: " << pt[0] << ", " << pt[1] << std::endl;
    std::cout << "ground truth: " << ground_truth[0] << ", " << ground_truth[1] << std::endl;
    int correct = 0, incorrect = 0;
    for(int i = 0; i < 100; ++i)
        tree.nearest_point(pt) == ground_truth ? ++correct : ++incorrect;
    std::cout << "correct: " << correct << ", incorrect: " << incorrect << std::endl;
}
```

```sh
> .\bin\Release\toy_test.exe
correct: 79, incorrect: 21
```

I am quite confused because the KDTree implementation will unlikely include any random elements.
I will try to figure out why by reading your code.

### PR DESCRIPTION
**Pull request by kn1cht**
Fix #12 

Fixed a bug in `KDTree::node_query_` that `k_nearest_buffer.insert()` might not be executed in certain environments when the next of `insert_it` is `k_nearest_buffer.end()`.

### CODE REVIEW

File: KDTree.cpp [hunk 1]
```diff
@@ -135,6 +135,7 @@ void KDTree::node_query_(
         std::upper_bound(k_nearest_buffer.begin(), k_nearest_buffer.end(),
                          node_distance, detail::compare_node_distance);
     if (insert_it == k_nearest_buffer.end() ||
+        std::next(insert_it) == k_nearest_buffer.end() ||
         insert_it->first != std::next(insert_it)->first) {
```
Comment (crvs) [inline KDTree.cpp]: this condition was wrong to begin with, it just doesn't make a difference in GCC for the reason you pointed out in the bug report, instead the insertion should happen when:

* `insert_it` is NOT the `end()`, or,
* `insert_it` is the `end()` pointer, but we still have not filled the buffer with `num_nearest` elements.

So the final insertion condition should be:
`(insert_it != k_nearest_buffer.end() || k_nearest_buffer.size() < num_nearest)`

**Review by crvs — APPROVED** [review]
Perfect!
